config/routes.rb
Rails.application.routes.draw do
  resources :photos

  get 'welcome/index'

  resources :articles do
    resources :comments
  end
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
            length: { minimum: 5 }
end

app/models/challenge.rb
class Challenge < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/image_uploader.rb
class ImageUploader < Shrine

end

app/models/photo.rb
class Photo < ApplicationRecord
  include ImageUploader[:image]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def index
    @challenges = Challenge.all
  end


  def save_checkbox
    @challenge = Challenge.find(params[:value])
    render json: "ok: #{params[:value]} = #{params[:checked]}"
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_box.html.erb
<div>
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <%= link_to article_path(article) do %>
              <strong><%= article.title %></strong>
          <% end %>
          <br>
          <%= truncate(sanitize(article.text, tags: %w(b strong em i)), length: 800) { link_to " Continue reading", "article_path(article)" } %>
        </p>
      </div>
      <nav class="level is-mobile">
        <div class="level-left">
          <a class="level-item">
            <%= link_to article_path(article) do %>
            <span class="icon is-small"><i class="fa fa-comment" aria-hidden="true"></i></span>
            <% end %>
          </a>
          <a class="level-item">
            <%= link_to edit_article_path(article) do %>
            <span class="icon is-small"><i class="fa fa-pencil" aria-hidden="true"></i></span>
            <% end %>
          </a>
          <a class="level-item">
            <%= link_to  article_path(article),
                         method: :delete,
                         data: { confirm: 'Are you sure?' } do %>
            <span class="icon is-small"><i class="fa fa-trash" aria-hidden="true"></i></span>
                <% end %>
          </a>
        </div>
      </nav>
    </div>
  </article>
</div>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_area :title, id: :post_title, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :text %>
      <%= f.hidden_field :text, id: :post_text, class: "form-control" %>
      <trix-editor input="post_text"></trix-editor>
    </div>
    <div class="button">
      <%= f.submit %>
    </div>




<% end %>

app/views/articles/edit.html.erb
<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1">

<section class="hero is-light">
  <div class="columns ">
    <div class="column is-offset-3 is-2 has-text-centered ">
      <%= link_to "Blog", articles_path, class: "button is-light is-medium is-fullwidth" %>
    </div>
    <div class="column  is-2 has-text-centered">
      <%= link_to "Home", welcome_index_path, class: "button is-light is-medium is-fullwidth" %>
    </div>
    <div class="column is-2 has-text-centered">
      <a class="button is-light is-medium is-fullwidth"><s>Videos</s></a>
    </div>
  </div>
</section>

<%= render 'form' %>

app/views/articles/index.html.erb
<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1">

<section class="hero is-light ">
  <div class="columns ">
    <div class="column is-offset-3 is-2 has-text-centered ">
      <%= link_to "Blog", articles_path, class: "button is-active is-light is-medium is-fullwidth" %>
    </div>
    <div class="column  is-2 has-text-centered">
      <%= link_to "Home", root_path, class: "button is-light is-medium is-fullwidth" %>
    </div>
    <div class="column is-2 has-text-centered">
      <a class="button is-light is-medium is-fullwidth"><s>Videos</s></a>
    </div>
  </div>
</section>

<section class="hero-body">
  <div class="columns">
    <div class="column is-offset-2 is-8 has-text-centered">
      <%= link_to 'New blogpost sooqa', new_article_path, class: "button is-outlined is-large[" %>

    </div>
  </div>
</section>



<% @articles.each do |article| %>
   <section class="hero is-light">
     <div class="hero-body">
       <div class="columns">
         <div class="column is-offset-2 is-8">
           <%= render partial: "box", locals: { article: article } %>
         </div>
       </div>
     </div>
   </section>
<% end %>

<section class="hero is-light">
  <div class="hero-body">
    <div class="columns">
      <div class="column">
        <div class="content has-text-centered">
          <p>Deeply inspired by my brother, that happens to be a professional code magician. Check out his page and give him some love: <a href="https://shovik.com/">shovik.com</a> </p>
        </div>
      </div>
      <div class="column has-text-centered i">
        <p>Contact me:</p>
        <a href="https://vk.com/hz_kto_eto"><i class="fa fa-vk fa-2x has-text-dark" aria-hidden="true"></i></a> <a href="https://github.com/Bylbanos"><i class="fa fa-github fa-2x has-text-dark" aria-hidden="true"></i></a><a href="https://www.facebook.com/jaroslav.kovshovik"> <i class="fa fa-facebook fa-2x has-text-dark" aria-hidden="true"></i></a>  <a href="https://www.instagram.com/bylbanos/?hl=ru"><i class="fa fa-camera-retro fa-2x has-text-dark" aria-hidden="true"></i></a>
      </div>
      <div class="column has-text-centered">
        <p><s>Proudly</s></p>
        <a href="https://bulma.io">
          <img src="https://bulma.io/images/made-with-bulma.png" alt="Made with Bulma" width="256" height="48">
        </a>
      </div>
    </div>
  </div>
</section>

app/views/articles/new.html.erb
<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1">

<section class="hero is-light">
  <div class="columns ">
    <div class="column is-offset-3 is-2 has-text-centered ">
      <%= link_to "Blog", articles_path, class: "button is-light is-medium is-fullwidth" %>
    </div>
    <div class="column  is-2 has-text-centered">
      <%= link_to "Home", welcome_index_path, class: "button is-light is-medium is-fullwidth" %>
    </div>
    <div class="column is-2 has-text-centered">
      <a class="button is-light is-medium is-fullwidth"><s>Videos</s></a>
    </div>
  </div>
</section>

<%= render 'form' %>

app/views/articles/show.html.erb
<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1">

<section class="hero is-light">
  <div class="columns ">
    <div class="column is-offset-3 is-2 has-text-centered ">
      <%= link_to "Blog", articles_path, class: "button is-light is-medium is-fullwidth" %>
    </div>
    <div class="column  is-2 has-text-centered">
      <%= link_to "Home", welcome_index_path, class: "button is-light is-medium is-fullwidth" %>
    </div>
    <div class="column is-2 has-text-centered">
      <a class="button is-light is-medium is-fullwidth"><s>Videos</s></a>
    </div>
  </div>
</section>


<section class="hero-body">
  <div class="hero">
    <div class="columns">
      <div class="column is-offset-2 is-8">
         <p class="title is-3 has-text-centered">
          <%= @article.title %>
         </p>
          <div class="content">
          <%= @article.text.html_safe%>
         </div>

      </div>
    </div>
  </div>
</section>




<br>
<br>
<br>
<br>


<section class="hero is-light">
  <div class="hero-body">
    <div class="columns">
      <div class="column is-offset-4 is-2">
        <%= link_to 'Edit', edit_article_path(@article), class: "button is-medium is-fullwidth" %>
      </div>
      <div class="column is-2">
        <%= link_to 'Back', articles_path, class: "button is-medium is-fullwidth" %>
      </div>
    </div>
  </div>
</section>

app/views/challenges/index.html.erb
<div class="pages index">
  <h2>Days</h2>

  <table class="Listing" summary ="Page list">
    <tr class="header">

      <th>#</th>
      <th>Description</th>
    </tr>
    <% @challenges.each do |challenge| %>
        <tr>
          <td><%= challenge.fasted %></td>
          <td><%= challenge.description %></td>
        </tr>
    <% end %>

    <div class="container">
      <input type="checkbox" class="checks" value= 1 > Save me!<br>

      <script>
        const checkboxes = document.querySelectorAll('input[type=checkbox]');

        function saveCheckbox(event) {
          const checkbox = event.target;

          $.get(`/challenges/save_checkbox?value=${checkbox.value}&checke=${checkbox.checked}`);
        }

        checkboxes.forEach(function(checkbox) {
          checkbox.addEventListener('change', saveCheckbox);
        })

      </script>
    </div>




  </table>
</div>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br>
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eric Kovshovik - QA Automation Engineer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :photo_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th>Image data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.image_data %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @photo.image_url %>
<p>
  <strong>Image data:</strong>
  <%= @photo.image_data %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/welcome/index.html.erb
<section class="hero is-primary is-bold is-fullheight">
  <div class="hero-body">
    <div class="container">
      <h1 class="title has-text-centered is-1">
        <a href="/Eric-Kovshovik-Resume.pdf">Eric Kovshovik</a>
      </h1>
      <h2 class="subtitle has-text-centered">
        QA Automation Engineer
      </h2>
    </div>
  </div>
</section>